### ISSUE TITLE
Segmentation fault when closing python process

### ISSUE THREAD

**Issue by hsogo** [belangeo/pyo#117] opened 2018-01-23 04:25 UTC
Hi belangeo,

I'm using pyo with PsychoPy and troubled with pyo's segmentation fault when closing python process.
In some modules in PsychoPy, pyo is imported but not used (e.g. to run `pyo.getVersion()` to check version of installed pyo).  In such case, segmentation fault occurs when python process is finished.  I'm not sure exact condition when segmentation fault occurs, but following operation causes segmentation error.

1. start python interpreter
2. run `import pyo`
3. run `s = pyo.Server()`
4. run `exit()`  - this causes segmentation fault.

I experienced this error in ubuntu 16.04LTS/python 3.6/pyo0.8.8.  The same operation causes Runtime Error in Windows10/python3.6/pyo0.8.8.  As for this example, I can safely close python process by running `s.boot()` before running `exit()`.  However, somewhat different issue seem to occur in PsychoPy modules.  For example, in `psychopy.info.RuntimeInfo._setSystemInfo()`, only doing `import pyo` and `pyo.getVersion()` causes segmentation fault.  Running these sentences on the python interpreter doesn't cause the error.  What is the reason for this segmentation fault?  What should I do to avoid this?

I'd appreciate your help.

--
Hiroyuki

**Comment by hsogo** [comment] 2018-01-24 12:24
I've fixed segmentation fault that occurs when Server is deleted before booted.
[https://github.com/hsogo/pyo/commit/96a4f293b69e6ac89a11f85c89625759b630f055](https://github.com/hsogo/pyo/commit/96a4f293b69e6ac89a11f85c89625759b630f055)
I confirmed that my fix works in ubuntu 16.04.  I want to examine whether my fix works in Windows, but building pyo in Windows seems quite hard according to your memo...  I'll try it later.

**Comment by belangeo** [comment] 2018-01-25 02:09
Hi,
I can confirm the segfault on my debian computer. And seeing your fix, that really makes sense. I missed it because I never create a Server without booting it! Same kind of segfault can also happen elsewhere so I will think of another way of handling this instead of checking for NULL everywhere. Anyway, thanks for reporting this bug, your fix is of great help! I'll try tomorrow on my windows computer but I'm almost sure that it will behave the same. I was planning a new release in a couple of days, I will include the fix for this bug.

**Comment by belangeo** [comment] 2018-01-25 02:12
```
import pyo
s = pyo.Server()
streams = s.getStreams()
```
Kaboum!

self->streams must really be initialized at the Server's creation.

**Comment by belangeo** [comment] 2018-01-25 15:01
> However, somewhat different issue seem to occur in PsychoPy modules. For example, in psychopy.info.RuntimeInfo._setSystemInfo(), only doing import pyo and pyo.getVersion() causes segmentation fault. Running these sentences on the python interpreter doesn't cause the error. What is the reason for this segmentation fault? What should I do to avoid this?

Does only `import pyo` in `psychopy.info.RuntimeInfo._setSystemInfo()` cause a segfault? I can't see why calling `pyo.getVersion()` can make any trouble... But the complete pyo inspection in this method includes a call to `pyo.pa_get_devices_infos()`: 

https://github.com/psychopy/psychopy/blob/65b034a16741e3737d070c28275d48a3a2520341/psychopy/info.py#L332

There were a bug `pyo.pa_get_devices_infos()` when a device name contained non-ascii characters. It's fixed in sources. Maybe the next version will fix this particular segfault in psychopy.

**Comment by hsogo** [comment] 2018-01-26 00:09
Oh, sorry, I'm working on my local repository of PsychoPy, in which `pyo.pa_get_devices_infos()` is commented out as following:

```
        # pyo for sound:
        try:
            travis = bool(str(os.environ.get('TRAVIS')).lower() == 'true')
            assert not travis  # skip sound-related stuff on travis-ci.org

            import pyo
            self['systemPyoVersion'] = '%i.%i.%i' % pyo.getVersion()
            # try:
            #     # requires pyo svn r1024 or higher:
            #     inp, out = pyo.pa_get_devices_infos()
            #     for devList in [inp, out]:
            #         for key in devList:
            #             if isinstance(devList[key]['name'], str):
            #                 devList[key]['name'] = devList[
            #                     key]['name'].decode(osEncoding)
            #     self['systemPyo.InputDevices'] = inp
            #     self['systemPyo.OutputDevices'] = out
            # except AttributeError:
            #     pass
        except (AssertionError, ImportError):
            pass
```
After commenting out, I run following script.  My systems are **Windows10/Python2.7.10/pyo0.8.8** and **Windows10/Python3.6.1(32bit)/pyo0.8.8**.

```
import psychopy.visual
import psychopy.info

win = psychopy.visual.Window(fullscr=False)
psychopy.info.RunTimeInfo(win=win)
```

This script stops working with following message.

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Additionally commenting out `import pyo` and `self['systemPyoVersion'] = '%i.%i.%i' % pyo.getVersion()`, the script run without error.  So I guess that pyo may be related to this error; however, there is no problem in importing pyo and running `pyo.getVersion()` directly from python interpreter.

**Comment by belangeo** [comment] 2018-01-26 00:13
What happens if you comment the line with `pyo.getVersion()` and only keep `import pyo` ?

**Comment by hsogo** [comment] 2018-01-26 01:28
The same error occurs.  So the problem seems to be in `import pyo`.

**Comment by belangeo** [comment] 2018-01-26 02:08
Well, it seems that pyo module does not like very much garbage collector. It is not a very good practice to import a module inside a function call... Why don't you just import it at the beginning of the module (inside a try-except statement to set a variable indicating if the import succeed or not) ?

**Comment by hsogo** [comment] 2018-01-26 08:17
PsychoPy supports several audio libraries and pyo is not necessarily installed.  `psychopy.info.RuntimeInfo()` checks whether pyo is installed.

By the way, I've reinstalled Python and installed only Pyo 0.8.8 and PsychoPy (and its dependency) to it.  Then `psychopy.info.RuntimeInfo()` worked without error!  This would be a good news, but it is still unclear what is the cause of the error.

**Comment by belangeo** [comment] 2018-01-26 15:36
> PsychoPy supports several audio libraries and pyo is not necessarily installed. psychopy.info.RuntimeInfo() checks whether pyo is installed.

For this kind of task, I prefer something like this:

```
try:
    import cv2
    FOUND_CV2 = True
except:
    FOUND_CV2 = False
```
> By the way, I've reinstalled Python and installed only Pyo 0.8.8 and PsychoPy (and its dependency) to it. Then psychopy.info.RuntimeInfo() worked without error! This would be a good news, but it is still unclear what is the cause of the error.

Well, pyo links to portaudio, as so does pyaudio and maybe sounddevice too, I don't know! So for sure, this is a good mix for conflicts!

**Closed** 2018-01-27 00:23 UTC
